name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install deps
      run: pnpm install

    - name: Build for node ${{ matrix.node-version }}
      run: pnpm run build

    - name: Prepare artifact
      run: bash -c 'echo -ne "#!/usr/bin/node\n" | cat - ./dist/bundle.js > /tmp/cli_${{ matrix.node_version}}.js'

    - name: Upload built CLI
      uses: actions/upload-artifact@v4.6.2
      with:
        name: CLI for node ${{ matrix.node-version }}
        path: /tmp/cli_${{ matrix.node_version}}.js

      
